// {
//     "id": 1,
//     "service_id": 2,
//     "city_id": 1,
//     "customer_name": "Lela gorelishvili",
//     "customer_email": "llgorelishvili@gmail.com",
//     "customer_phone": "+393891496149",
//     "street_name": "via giovanni giorgi",
//     "house_number": "5",
//     "property_size": "40",
//     "doorbell_name": "Lela gorelishvili",
//     "booking_date": "2026-02-04",
//     "booking_time": "14:00",
//     "hours": 2,
//     "cleaners": 2,
//     "total_amount": 19,
//     "payment_intent_id": "pi_3Sxm6IKEJbAqCpEe1WsxbEal",
//     "notes": null,
//     "additional_services": [],
//     "supplies": [
//       "provide-solvents",
//       "provide-mop",
//       "provide-vacuum"
//     ],
//     "status": "confirmed",
//     "stripe_status": "captured",
//     "created_at": "2026-02-05T22:17:26.318Z",
//     "updated_at": "2026-02-05T22:19:05.800Z"
//   },
